name: upload gatsby app from github to VM ubuntu
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: install node js
      run: sudo apt install nodejs
      
    - name: install dependencies
      run: npm install 
      
    - name: install gatsby
      run: npm install -g gatsby-cli
      
    - name: check Gatsby Version
      run: gatsby --version
      
    - name: build Gatsby app
      run: gatsby build
      
    - name: confirm public folder
      run: ls -la public
    
    - name: upload public folder as package 
      uses: actions/upload-artifact@v3  
      with: 
        name: public-package
        path: public
      
  deploy:
    runs-on: ubuntu-latest
    needs: SecurityCA
    steps:
    - name: download public folder to this deploy job
      uses: actions/download-artifact@v3
      with:
        name: public-package
        path: public
      
    - name: Copy the Public Folder of gatsby app to Ubuntu
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
          local: 'public/*'
          remote: '~/public/'
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: sudo rm -rf /var/www/html/*
          post_upload: sudo mv ~/public/* /var/www/html/
          
  SecurityCA:
      runs-on: ubuntu-latest
      needs: build
      steps: 
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name: do audit
        run: npm audit --json > /audit_repo.json
        #continue-on-error: true
        
      - name: list down files
        run: ls -la
        
      - name: archive npm audit file & upload
        uses: actions/upload-artifact@v3
        with:
          name: npm audit file
          path: audit_repo.json
        if: always()
      
