# This is a basic workflow that is manually triggered

name: upload gatsby app from github to VM ubuntu

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: install node js
      run: sudo apt install nodejs
      
    - name: install dependencies
      run: npm install
      
    - name: install gatsby
      run: npm install -g gatsby-cli
      
    - name: check Gatsby Version
      run: gatsby --version
      
    - name: build Gatsby app
      run: gatsby build
      
    - name: confirm public folder
      run: ls -la public
      
    - name: Copy the Public Folder of gatsby app to Ubuntu
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
          local: 'public/*'
          remote: '~/public/'
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: sudo rm -rf /var/www/html/*
          post_upload: sudo mv ~/public/* /var/www/html/ 
